# Generated by Django 2.0.5 on 2018-05-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_buddy', '0003_auto_20180521_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='users_on_trip',
            field=models.ManyToManyField(related_name='have_joined', to='travel_buddy.User'),
        ),
    ]
