# Generated by Django 2.1.4 on 2019-01-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_destination_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
